#!/bin/sh

# -------------------------- CUT THIS SECTION ---------------------------
#  This is a template to create a customized plugin
#
#  Each plugin should at least have several variables defined with the
#  prefix PLUGIN_* (see below)
#
#  If you want to learn what functions you can use, check include/functions
#
# -------------------------- CUT THIS SECTION ---------------------------

#########################################################################
#
#    * DO NOT REMOVE *
#-----------------------------------------------------
# PLUGIN_AUTHOR=___nancheal_nancheal@gmail.com___
# PLUGIN_CATEGORY=Cust
# PLUGIN_DESC=A test gather information for Computer forensics or Privilege escalation
# PLUGIN_NAME=information_gather
# PLUGIN_REQUIRED_TESTS=SCHD-7704
#-----------------------------------------------------
#
#########################################################################
#
    # Add custom section to screen output
    InsertSection "Custom "
#
# get /ect/passwd
function get_etc_passwd(){
    IFS=$'\n'
    passwd_content=$(${AWKBINARY} '{print $0}' /etc/passwd)
    LogText "Test:obtain /etc/passwd file content"
    for each_passwd in ${passwd_content};
    do
        Report "passwd_file[]=$each_passwd"
    done
}
# get hidden file path
function get_hidden_file(){
    hidden_file=$(find / -name ".*" -type f -path "/*" -exec ls -al {} \; 2>/dev/null)
    LogText "Test:obtain hidden file path"
    for each_file in ${hidden_file};
    do
        Report "hidden_file[]=$each_file"
    done   
}
#################################################################################
#
    # Test        : CUST-8090
    # Description : A test gather information for Computer forensics or Privilege escalation

    # Register our first custom test
    # We consider it to be a lightweight test (no heavy IO, or long searches), no network connection needed
    Register --test-no CUST-8090 --weight L --network NO --description "A test gather information for Computer forensics or Privilege escalation"
    if [ ${SKIPTEST} -eq 0 ]; then
        # The Display function makes it easy to show something on screen, with colors.
        # --indent  defines amount of spaces
        # --text    text to be displayed on screen
        # --result  text at end of line
        # --color   color of result text
        Display --indent 2 --text "- Checking if everything is OK..." --result OK --color GREEN
        Display --indent 4 --text "This shows one level deeper " --result NOTICE --color YELLOW
        Display --indent 6 --text "And even deeper" --result WARNING --color RED
        get_etc_passwd;
        get_hidden_file;
        # Show a warning on screen and in the report. We can specify a detail and how to solve it.
        ReportWarning "${TEST_NO}" "Something was wrong and should be fixed" "/etc/motd" "text:Change your motd"
        ReportSuggestion "${TEST_NO}" "Check if this process is running" "apache" "url:https://cisofy.com/support/"
    fi
#
#################################################################################
#

    # First check if OPENSSLBINARY is known as a prerequisite for this test.
    if [ ! -z "${OPENSSLBINARY}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no CUST-0001 --preqs-met ${PREQS_MET} --weight M --network NO --description "Description of custom test"
    if [ ${SKIPTEST} -eq 0 ]; then
        FOUNDPROBLEM=0
        DIR="/my/path"
        LogText "Test: we are going to check if we can find a particular directory (${DIR})"
        # Check if a directory exists
        if [ -d ${DIR} ]; then
            LogText "Result: log entry for easier debugging or additional information"
        else
            FOUNDPROBLEM=1
            LogText "Result: directory ${DIR} was not found!"
            ReportWarning "${TEST_NO}" "This is a test warning line" "${DIR}" "text:Create directory ${DIR}"
        fi

        if [ ${FOUNDPROBLEM} -eq 0 ]; then
            Display --indent 2 --text "- Checking if everything is OK..." --result OK --color GREEN
        else
            Display --indent 2 --text "- Checking if everything is OK..." --result WARNING --color RED
            ReportSuggestion ${TEST_NO} "This is a suggestion"
        fi
    fi
#
#################################################################################
#

# Wait for keypress (unless --quick is being used)
WaitForKeyPress

#EOF