#!/bin/sh

#########################################################################
#
#    * DO NOT REMOVE *
#-----------------------------------------------------
# PLUGIN_AUTHOR=___nancheal_nancheal@gmail.com___
# PLUGIN_CATEGORY=Custom
# PLUGIN_DESC=A test gather /etc/passwd file content
# PLUGIN_NAME=get_passwd
# PLUGIN_REQUIRED_TESTS=
#-----------------------------------------------------
#
#########################################################################
#
    # Add custom section to screen output
    InsertSection "get passwd"
#
#################################################################################
#
    # Test        : CUST-0001
    # Description : A test gather /etc/passwd file content

    # Register our first custom test
    # We consider it to be a lightweight test (no heavy IO, or long searches), no network connection needed
    Register --test-no CUST-0001 --weight L --network NO --description "A test gather /etc/passwd file content"
    if [ ${SKIPTEST} -eq 0 ]; then
        # The Display function makes it easy to show something on screen, with colors.
        # --indent  defines amount of spaces
        # --text    text to be displayed on screen
        # --result  text at end of line
        # --color   color of result text
        Display --indent 2 --text "- collecting /etc/passwd file content..." --result OK --color GREEN
        passwd_content=$(awk '{print $0}' /etc/passwd)
        LogText "Test:obtain /etc/passwd file content"
        for each_passwd in ${passwd_content};
        do
            IFS=$'\n'
            Report "passwd_file[]=$each_passwd"
        done
    fi
#
#

# Wait for keypress (unless --quick is being used)
WaitForKeyPress

#EOF