#!/bin/sh

# -------------------------- CUT THIS SECTION ---------------------------
#  This is a template to create a customized plugin
#
#  Each plugin should at least have several variables defined with the
#  prefix PLUGIN_* (see below)
#
#  If you want to learn what functions you can use, check include/functions
#
# -------------------------- CUT THIS SECTION ---------------------------

#########################################################################
#
#    * DO NOT REMOVE *
#-----------------------------------------------------
# PLUGIN_AUTHOR=___nancheal_nancheal@gmail.com___
# PLUGIN_CATEGORY=PASS
# PLUGIN_DESC=A test for check if there is password hashes stored in /etc/passwd and if /etc/passwd is writeable also if /etc/shadow is readable
# PLUGIN_NAME=check_passwd_shadow
# PLUGIN_REQUIRED_TESTS=
#-----------------------------------------------------
#
#########################################################################

check_password_hashes() {
    # define some constant
    IFS_OLD=$IFS
    IFS=$'\n'
    ENCRYPTEDPASS='x' 
    #start
    LogText "Test:obtain /etc/passwd file content"
    passwd_content=$(${AWKBINARY} '{print $0}' /etc/passwd)
    for each_passwd in ${passwd_content};
    do
        IFS=':'
        passwd_split_colon=($each_passwd)
        if [ "${passwd_split_colon[1]}" != "$ENCRYPTEDPASS" ];then
            IFS=$'\n'
            Report "sensetive_passwd_hashes[]=$each_passwd"
        fi
    done
    IFS=$IFS_OLD
}

check_passwd_writeable() {
    #start
    LogText "Test:obtain /etc/passwd file permission in number format"
    passwd_permission_number=$(stat -c %a /etc/passwd)
    if [ "$passwd_permission_number" -gt "644" ];then
        Report "passwd_writeable[]=$(ls -la /etc/passwd)"
    fi
}

check_shadow_readable() {
    #start
    LogText "Test:obtain /etc/shadow file permission in number format"
    shadow_permission_number=$(stat -c %a /etc/shadow)
    if [ "$shadow_permission_number" -gt "640" ];then
        Report "shadow_readable[]=$(ls -la /etc/shadow)"
    fi
}
#########################################################################
#
    # Add custom section to screen output
    InsertSection "PASS"
#
#################################################################################
#
    # Test        : PASS-0001
    # Description : We show some lines on the screen

    # Register our first custom test
    # We consider it to be a lightweight test (no heavy IO, or long searches), no network connection needed
    Register --test-no PASS-0001 --weight L --network NO --description "A test for check if there is password hashess stored in /etc/passwd"
    if [ ${SKIPTEST} -eq 0 ]; then
        # The Display function makes it easy to show something on screen, with colors.
        # --indent  defines amount of spaces
        # --text    text to be displayed on screen
        # --result  text at end of line
        # --color   color of result text
        Display --indent 2 --text "- Checking if there is a password hashes on /etc/passwd file" --result OK --color GREEN
        check_password_hashes;
    fi
#
#################################################################################
#
    # Test        : PASS-0002
    # Description : We show some lines on the screen

    # Register our first custom test
    # We consider it to be a lightweight test (no heavy IO, or long searches), no network connection needed
    Register --test-no PASS-0002 --weight L --network NO --description "A test for check if /etc/shadow is readable"
    if [ ${SKIPTEST} -eq 0 ]; then
        # The Display function makes it easy to show something on screen, with colors.
        # --indent  defines amount of spaces
        # --text    text to be displayed on screen
        # --result  text at end of line
        # --color   color of result text
        Display --indent 2 --text "- Checking if /etc/shadow is readable" --result OK --color GREEN
        check_shadow_readable;
    fi
#
#################################################################################
#
    # Test        : PASS-0003
    # Description : We show some lines on the screen

    # Register our first custom test
    # We consider it to be a lightweight test (no heavy IO, or long searches), no network connection needed
    Register --test-no PASS-0003 --weight L --network NO --description "A test for check if /etc/passwd is writeable"
    if [ ${SKIPTEST} -eq 0 ]; then
        # The Display function makes it easy to show something on screen, with colors.
        # --indent  defines amount of spaces
        # --text    text to be displayed on screen
        # --result  text at end of line
        # --color   color of result text
        Display --indent 2 --text "- Checking if /etc/passwd is writeable" --result OK --color GREEN
        check_passwd_writeable;
    fi
#
#################################################################################
# Wait for keypress (unless --quick is being used)
WaitForKeyPress

#EOF
